sudo: true
dist: trusty
language: node_js
node_js: 8.9

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  google-chrome: latest

install:
  - npm install
  - bower install

before_script:
  - gulp lint
  - polymer lint --rules polymer-2 --input *.html
  - xvfb-run -s '-screen 0 1024x768x24' wct

script:
  - if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" && "$TRAVIS_BRANCH" != quick/* ]]; then
      wct --env saucelabs;
      rm package.json;
      modulizer --npm-name @vaadin/vaadin-themable-mixin --npm-version 0.0.0 --out modulizer_out --force;
      mv package.json modulizer_out;
      (cd modulizer_out && npm i);
      polymer test --npm --env saucelabs-p3 --root modulizer_out;
    fi
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
      wct --env saucelabs-cron;
    fi
